### ISSUE TITLE
Max Pub/Sub Client Connections

### ISSUE THREAD

**Issue by sgoveia** [kubemq-io/kubemq#5]
Very cool project @kubemq! Wondering about benchmarks for max client connections when using the Pub/Sub pattern in the community edition(3 nodes)? Looking to use your python lib. Thanks!

**Comment by kubemq** [comment]
Thank you,
The limit of conenctions are the limitation of the underline infrastructure
such as Kubernetes, networking etc
KubeMQ is written in Go so you get the benefits of very high scale
connectivity features

**Comment by sgoveia** [comment]
Thanks!
